sudo: required
dist: trusty

before_install:
 - wget https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-mdk.zip
 - unzip -n forge-1.12.2-14.23.5.2768-mdk.zip
 - rm forge-1.12.2-14.23.5.2768-mdk.zip

language: java
jdk:
 - oraclejdk8
 - openjdk8

cache:
 directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
  - '$HOME/.gradle/wrapper'
  - '$HOME/.gradle/caches'

addons:
 sonarcloud:
  organization: "appliedenergistics"

install: "./gradlew setupCIWorkspace"
script:
 - "./gradlew build"
 - "./gradlew test"
 - "./gradlew sonarqube"
