sudo: required
dist: trusty

language: java
jdk:
 - oraclejdk8
 - openjdk8

cache:
 directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
  - '$HOME/.gradle/wrapper'
  - '$HOME/.gradle/caches'

addons:
 sonarcloud:
  organization: "appliedenergistics"

script:
 - "./gradlew build"